### ISSUE TITLE
Feature Request: Making dark mode for website "arakoo.ai" and some other enhancements

### ISSUE THREAD

**Issue by yaten2302** [arakoodev/doc#36]
Hi @sandys, I am planning to make this website's dark mode and some other enhancements like - borders of buttons, and the styling the nav bar.

Please assign this issue to me under GSSOC'23 as I want to work on it. 🙏🙏

**Comment by sandys** [comment]
@yaten2302 can u please DM me on discord. will want to discuss this in detail before getting started.

**Comment by yaten2302** [comment]
Hi @sandys, could you please send me your discord ID, so that I can send you friend request 🙏

**Comment by sandys** [comment]
@yaten2302 please join here https://discord.gg/DuR9gzYm

**Comment by yaten2302** [comment]
Hi @sandys , I have sent you the friend request. Could you please check that I have sent it to you only or sent it to someone else by mistake😂
