### ISSUE TITLE
BOUNTY: improve docs

### ISSUE THREAD

**Issue by sandys** [arakoodev/doc#71]
Our docs are outdated and written a long time back. here's our main repo - https://github.com/arakoodev/edgechains

**Describe your ideal solution**
1. Try out edgechains
2. Rewrite our docs in a better
 way

Goal - is for first time users to be able to quickly create their first application using Edgechains.

P.S. if you hit any bugs or problems while using it, we will fix it. 

Ideally you should be someone who knows java. But even if you are not, you need to be able to learn quickly and write little bit of java to be able to use edgechains.
Please do not do this bounty if you are not running edgechains and simply rewriting docs using chatgpt. that will not be acceptable.

**HOW TO USE**
this doc system is built on docusaurus. It automatically builds. All you have to do is change the docs inside "docs" directory using markdown.
If you fork this site, you will see that it automatically builds using actions.

**Comment by WcaleNieWolny** [comment]
How much of a rewrite arę you expecting? A whole docs or just improvements to all of the Pages (Like updating them to work on the latest version or making them more clean ear)

**Comment by sandys** [comment]
we will be expecting a rewrite. the docs are not that big. Its about 7-8 pages for the technical part.

Pages like https://www.arakoo.com/doc/Community_and_Support are not important.

**Comment by WcaleNieWolny** [comment]
So pages like: Endpoint Documentation, Example API for edgechains,edgechains modules, tutorials and techniques and quickstart?

**Comment by Wholesomebruh** [comment]
> we will be expecting a rewrite. the docs are not that big. Its about 7-8 pages for the technical part.
> 
> Pages like https://www.arakoo.com/doc/Community_and_Support are not important.

@sandys Any important details to add?

**Comment by sandys** [comment]
@Wholesomebruh its a full rewrite. so there's no particular details to focus on.

**Comment by sandys** [comment]
folks, please remember that the pre-requisite for working on this bounty is to be able to run Edgechains. Please do NOT begin writing docs unless you have been able to run it.

if you have any doubts, please ask us on Discord

https://discord.gg/ZWvqHh7R

**Comment by sandys** [comment]
bounty closed because of no work submitted.
