### ISSUE TITLE
Grammatical and spelling errors in the Privacy policy section

### ISSUE THREAD

**Issue by HimanshuNarware** [arakoodev/doc#8]
##Description
The website content has lots of grammatical and spelling errors, and I want to resolve them, Kindly assign me this issue.

##Screenshot

![96](https://github.com/arakoodev/EdgeChains/assets/83147410/14215716-0282-45cd-91fc-9d73b44d7968)

**Comment by sandys** [comment]
@HimanshuNarware please fix and close.

**Comment by Bhanuteja01** [comment]
@sandys can i do this!
im gssoc contributor

**Comment by sandys** [comment]
@Bhanuteja01 thanks for your interest, however the issue was created by @HimanshuNarware . 

Please feel free to create new issues (which are not same as this) and ill be happy to assign it to you!
